spring:
  application:
    name: config-server-service

  cloud:
    config:
      server:
        native:
          # Order of locations searched for config files
          search-locations:
            - file:./config-repo
            - classpath:/config-repo

  profiles:
    active: native

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

server:
  port: 8888

eureka:
  client:
    enabled: false



