-- V3__Insert_additional_users.sql
-- Additional users and roles (if any) from 01-setup-auth-database.sql not already in V2
-- No additional users/roles needed as all are covered in V2 after update.
-- This file can be used for future user/role additions if needed. 