# Bootstrap Configuration - Only essential config needed before connecting to config server
spring:
  application:
    name: pharmacy-management-service
  config:
    import:
      - "optional:configserver:http://localhost:8888"
      - "optional:file:C:/Users/CM/Downloads/Compressed/Hospital Management System/backend (hms)/.env[.properties]" 