# Docker-specific configuration for API Gateway Service
server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # Global CORS Configuration
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173,http://frontend:80"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true

      # Route Configuration for Docker with Eureka Service Discovery
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**

        - id: appointment-scheduling-service
          uri: lb://appointment-scheduling-service
          predicates:
            - Path=/appointments/**

        - id: patient-management-service
          uri: lb://patient-management-service
          predicates:
            - Path=/patients/**

        - id: doctor-management-service
          uri: lb://doctor-management-service
          predicates:
            - Path=/doctors/**

        - id: ehr-reports-service
          uri: lb://ehr-reports-service
          predicates:
            - Path=/reports/**

        - id: billing-invoicing-service
          uri: lb://billing-invoicing-service
          predicates:
            - Path=/invoices/**

        - id: pharmacy-management-service
          uri: lb://pharmacy-management-service
          predicates:
            - Path=/pharmacy/**

# Security Configuration
app:
  jwt:
    secret: ${JWT_SECRET}

# Eureka Configuration for Docker
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: api-gateway

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
    com.pro.apigatewayservice: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 