# Development Environment Configuration
# This file contains configurations specific to the development environment

# Development Logging - More verbose for debugging
logging:
  level:
    com.pro: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Development JPA Settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Development CORS - More permissive
app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000

# Development Actuator - Full exposure for debugging
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*" 