# Production Environment Configuration
# This file contains configurations specific to the production environment

# Production Logging - Less verbose, focused on important events
logging:
  level:
    com.pro: INFO
    org.springframework.security: WARN
    org.springframework.cloud.gateway: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN

# Production JPA Settings - More conservative
spring:
  jpa:
    hibernate:
      ddl-auto: validate  # Never auto-update schema in production
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# Production CORS - Restrictive
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}  # Must be explicitly set

# Production Actuator - Limited exposure for security
management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

# Production Database Pool - Optimized for performance
spring:
  datasource:
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:10}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:20000}
      idle-timeout: ${DB_IDLE_TIMEOUT:300000}
      max-lifetime: ${DB_MAX_LIFETIME:1200000} 