# Docker-specific configuration for Patient Management Service
server:
  port: 8084

spring:
  # PostgreSQL Database Configuration for Docker
  datasource:
    url: jdbc:postgresql://postgres:5432/hms_patient_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # MongoDB Configuration for Docker
  data:
    mongodb:
      uri: mongodb://localhost:27017/hms_medical_history_db
      auto-index-creation: true
  
  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET}
  cors:
    allowed-origins: http://localhost:5173,http://frontend:80

# Stroke Prediction Service Configuration
stroke:
  prediction:
    service:
      url: http://stroke-prediction-service:8090
    use:
      discovery: true

# Eureka Configuration for Docker
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server-service:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: patient-management-service

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  health:
    db:
      enabled: true
    mongo:
      enabled: true

# Logging Configuration
logging:
  level:
    com.pro.patientmanagementservice: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.springframework.data.mongodb: INFO
    org.flywaydb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 