# Development Configuration for Pharmacy Management Service
spring:
  # JPA Configuration for Development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Logging Configuration for Development
logging:
  level:
    com.pro.pharmacymanagementservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.jpa: DEBUG
    org.springframework.web: DEBUG

# Development specific pharmacy configurations
pharmacy:
  inventory:
    low-stock-threshold: 5
    expiry-warning-days: 7
    auto-update-status: true
  prescription:
    auto-generate-number: true
    require-doctor-verification: false  # Relaxed for development
  notifications:
    enabled: false  # Disabled for development

# Development CORS settings (more permissive)
app:
  cors:
    allowed-origins: "*" 