# Server Configuration
server:
  port: ${SERVER_PORT_PHARMACY:8087}

# Spring Configuration
spring:
  # PostgreSQL Database Configuration for Pharmacy Data
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${PHARMACY_DB_NAME:hms_pharmacy_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      leak-detection-threshold: ${DB_LEAK_DETECTION:60000}
  
  # JPA Configuration for PostgreSQL
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  # Flyway Configuration - Disabled for local development
  flyway:
    enabled: false

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET}  # Must be provided via environment variable
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:localhost}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  health:
    db:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.pro.pharmacymanagementservice: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:WARN}
    org.springframework.data.jpa: ${LOG_LEVEL_JPA:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Pharmacy specific configurations
pharmacy:
  inventory:
    low-stock-threshold: ${PHARMACY_LOW_STOCK_THRESHOLD:10}
    expiry-warning-days: ${PHARMACY_EXPIRY_WARNING_DAYS:30}
    auto-update-status: ${PHARMACY_AUTO_UPDATE_STATUS:true}
  prescription:
    auto-generate-number: ${PHARMACY_AUTO_GENERATE_NUMBER:true}
    require-doctor-verification: ${PHARMACY_REQUIRE_DOCTOR_VERIFICATION:true}
  notifications:
    enabled: ${PHARMACY_NOTIFICATIONS_ENABLED:true}
    email:
      enabled: ${PHARMACY_EMAIL_NOTIFICATIONS:false} 