# Server Configuration for Docker
server:
  port: 8087

# Spring Configuration for Docker Environment
spring:
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/${PHARMACY_DB_NAME:hms_pharmacy_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      leak-detection-threshold: 60000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET}


# Eureka Configuration for Docker
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: pharmacy-management-service
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90



# Logging Configuration for Docker
logging:
  level:
    com.pro.pharmacymanagementservice: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.data.jpa: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

